services:
  postgres:
    image: postgres:18
    container_name: cart-pg
    environment:
      POSTGRES_USER: cart_user
      POSTGRES_PASSWORD: cart_pass
      POSTGRES_DB: cartdb
      sslmode: disable
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cart_user -d cartdb"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pgdata:
